### ISSUE TITLE
What is Thinktecture.IdentityModel.Core used for?

### ISSUE THREAD

**Issue by Shazwazza** [mattbrailsford/UmbracoIdentity.OAuth#4]
Not sure what this package is doing? In IdentityExtensions we use the built in ASP.NET Identity token server which uses JWT and is fully extensible, are you following that same principal?

**Comment by mattbrailsford** [comment]
Looks like I was purely using it for the HmacSigningCredentials class. I've copied that class over as it's really rather simple and removed the dependency.
